
[[constraint]]
  branch = "master"
  name = "github.com/fsouza/go-dockerclient"

[[override]]
  name = "github.com/docker/docker"
  source = "https://github.com/moby/moby.git"
  revision = "17bb1d3663f6586e83b453670526e3186bb56dd3"
